version: '2'
services:
  visio-app:
    image: visio
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://visio-mssql:1433;database=visio
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://visio-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://visio-elasticsearch:9200
    ports:
      - 8080:8080
  visio-mssql:
    extends:
      file: mssql.yml
      service: visio-mssql
  visio-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: visio-elasticsearch
